/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formadmin;

import controller.*;
import entitas.*;
import tiket.bioskop.*;
import java.awt.Color;
import formadmin.login;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ilham Bayu Sabdani
 */
public class datatrans extends javax.swing.JFrame {

    /**
     * Creates new form COVER
     */
    private ArrayList<Pilih> arrPilih;
    private ArrayList<Have> arrHave;
    private modelpembeli beli;
    int dragx,dragy;
    
    public datatrans() throws SQLException {
        initComponents();
        this.beli = new modelpembeli();
        this.arrPilih = new ArrayList<>();
        this.arrHave = new ArrayList<>();
        this.showTableTransaksi();
        this.showTableTransaksi2();
        this.showTableTransaksi3();
        this.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        datatrans3 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        datatrans1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        datatrans2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        datatrans3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(datatrans3);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(450, 80, 340, 250);

        datatrans1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(datatrans1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 80, 260, 250);

        datatrans2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(datatrans2);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(270, 80, 180, 250);

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(570, 360, 90, 23);

        jLabel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel2MouseDragged(evt);
            }
        });
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 410);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/umum.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 410);

        setBounds(0, 0, 800, 414);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseDragged
        
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - dragx,y - dragy);
    }//GEN-LAST:event_jLabel2MouseDragged

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        dragx = evt.getX();
        dragy = evt.getY();
    }//GEN-LAST:event_jLabel2MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new MENU1().setVisible(true);
            setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void showTableTransaksi() throws SQLException {
        DefaultTableModel dtmTrans = new DefaultTableModel(new String[]{
            "KODE", "NAMA USER", "BANYAK"
        }, 0);
        dtmTrans.setRowCount(0);
        for (Transaksi tr : this.beli.getDataTransaksi()) {            
            dtmTrans.addRow(new String[]{
                tr.getKode_Tiket().toString(),
                tr.getreg().getpembeli().getNama(),
                tr.getBanyak().toString(),
            });
        }
        this.datatrans1.setModel(dtmTrans);
    }

    private void showTableTransaksi2() throws SQLException {
        DefaultTableModel dtmTrans2 = new DefaultTableModel(new String[]{
            "DUDUK"
        }, 0);
        dtmTrans2.setRowCount(0);
        for (Pilih pl : this.beli.getDataDUDUK()) {            
            dtmTrans2.addRow(new String[]{   
                pl.gettpt().getDuduk()
            });
        }
        this.datatrans2.setModel(dtmTrans2);
    }

    private void showTableTransaksi3() throws SQLException {
        DefaultTableModel dtmTrans3 = new DefaultTableModel(new String[]{
            "FILM", "TGL TAYANG", "WAKTU TAYANG", "TOTAL"
        }, 0);
        dtmTrans3.setRowCount(0);
        for (Have hv : this.beli.getDatacinema()) {            
            dtmTrans3.addRow(new String[]{
                hv.getjdwl().getFilm().getNama_Film(),
                hv.getjdwl().getTgl_Tayang().toString(),
                hv.getjdwl().getWktu_Tayang(),
                hv.gettotal().toString()
            });
        }
        
        this.datatrans3.setModel(dtmTrans3);
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datatrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datatrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datatrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datatrans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new datatrans().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(datatrans.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable datatrans1;
    private javax.swing.JTable datatrans2;
    private javax.swing.JTable datatrans3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
