/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formadmin;

import controller.*;
import entitas.*;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import tiket.bioskop.COVER;

/**
 *
 * @author Ilham Bayu Sabdani
 */
public class jadwal extends javax.swing.JFrame {

    private modelcinema cinema;
    
    int dragx,dragy;
    public jadwal() throws SQLException {
        initComponents();
        this.cinema = new modelcinema();
        this.showComboBoxFilm();
        this.showTableJadwal();
//        tabel1.setModel(data07065.datajadwal.viewTabel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        pilihfilm = new javax.swing.JComboBox();
        ruangan = new javax.swing.JComboBox();
        waktu = new javax.swing.JComboBox();
        tanggal = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel1 = new javax.swing.JTable();
        insert = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kodejadwal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel8.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ruang");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 400, 110, 20);
        getContentPane().add(pilihfilm);
        pilihfilm.setBounds(40, 190, 330, 30);

        ruangan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "TEATER 1", "TEATER 2", "TEATER 3", "TEATER 4", "TEATER 5" }));
        getContentPane().add(ruangan);
        ruangan.setBounds(40, 430, 330, 30);

        waktu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "08.00", "12.00", "15.00", "18.00" }));
        getContentPane().add(waktu);
        waktu.setBounds(40, 350, 330, 30);

        tanggal.setForeground(new java.awt.Color(255, 255, 255));
        tanggal.setText("dd/MM/yyyy");
        tanggal.setOpaque(false);
        getContentPane().add(tanggal);
        tanggal.setBounds(40, 270, 330, 30);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/EXIT.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(370, 0, 50, 50);

        tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        jScrollPane1.setViewportView(tabel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 480, 400, 90);

        insert.setBackground(new java.awt.Color(0, 204, 204));
        insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/UPDATE.png"))); // NOI18N
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        getContentPane().add(insert);
        insert.setBounds(20, 590, 110, 50);

        delete.setBackground(new java.awt.Color(204, 0, 51));
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/DELETE.png"))); // NOI18N
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(150, 590, 110, 50);

        update.setBackground(new java.awt.Color(0, 204, 204));
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/INSERT.png"))); // NOI18N
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(280, 590, 110, 50);

        jLabel6.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Waktu Tayang");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 320, 110, 20);

        jLabel5.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tanggal Tayang");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 240, 120, 20);

        jLabel4.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Film");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 160, 80, 20);

        kodejadwal.setForeground(new java.awt.Color(255, 255, 255));
        kodejadwal.setText("jadwal code");
        kodejadwal.setOpaque(false);
        getContentPane().add(kodejadwal);
        kodejadwal.setBounds(40, 110, 320, 30);

        jLabel2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Jadwal");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 80, 100, 20);

        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel7MouseDragged(evt);
            }
        });
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 420, 650);

        jLabel3.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("JADWAL FILM");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 20, 250, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/FORM REG.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 650);

        setSize(new java.awt.Dimension(417, 651));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        DefaultTableModel model = (DefaultTableModel) tabel1.getModel();
        int i = tabel1.getSelectedRow();
        kodejadwal.setText(model.getValueAt(i, 0).toString());
        
        try {
            this.cinema.updatejdwl(Integer.parseInt(kodejadwal.getText()),waktu.getSelectedItem().toString());
            this.showTableJadwal();
        } catch (SQLException ex) {
            Logger.getLogger(MANAGEFILM.class.getName()).log(Level.SEVERE, null, ex);
        }        

    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) tabel1.getModel();
        int i = tabel1.getSelectedRow();
        Integer jwl = Integer.parseInt(model.getValueAt(i, 0).toString());
        try {
            this.cinema.deletejdwl(jwl);
            this.showTableJadwal();
        } catch (SQLException ex) {
            Logger.getLogger(MANAGEFILM.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_deleteActionPerformed
    private void kosong()
    {
        kodejadwal.setText("");
        tanggal.setText("");
    }
    
    private void showTableJadwal() throws SQLException {
        DefaultTableModel dtmJadwal = new DefaultTableModel(new String[]{
            "KODE JADWAL", "NAMA FILM", "TANGGAL TAYANG", "WAKTU TAYANG", "RUANG"
        }, 0);
        dtmJadwal.setRowCount(0);

        for (Jadwal jd : this.cinema.getDataJadwal()) {
            dtmJadwal.addRow(new String[]{
                jd.getKode_Jadwal().toString(),
                jd.getFilm().getNama_Film(),
                jd.getTgl_Tayang().toString(), 
                jd.getWktu_Tayang(),
                jd.getRuang()
            });
        }
        this.tabel1.setModel(dtmJadwal);
    }
    
    private void showComboBoxFilm() throws SQLException {
        DefaultComboBoxModel dcbmFilm = new DefaultComboBoxModel();

        for (Film f : this.cinema.getDataFilm()) {
            dcbmFilm.addElement(f.getNama_Film());
        }
        this.pilihfilm.setModel(dcbmFilm);
    }
    
    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        Jadwal jadwal = new Jadwal();
        try {
            jadwal.setfilm(cinema.getDataFilm().get(pilihfilm.getSelectedIndex()));
            jadwal.setKode_Jadwal(Integer.parseInt(kodejadwal.getText()));
            jadwal.setTgl_Tayang(new SimpleDateFormat("dd/MM/yyyy").parse(tanggal.getText()));
            jadwal.setWktu_Tayang(waktu.getSelectedItem().toString());
            jadwal.setRuang(ruangan.getSelectedItem().toString());
            
            this.cinema.insertjdwl(jadwal);
            this.showTableJadwal();
            kosong();
        } catch (SQLException | ParseException err) {
            System.out.println(err);
        } 
        
    }//GEN-LAST:event_insertActionPerformed

    private void jLabel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - dragx,y - dragy);
    }//GEN-LAST:event_jLabel7MouseDragged

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        dragx = evt.getX();
        dragy = evt.getY();
    }//GEN-LAST:event_jLabel7MousePressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     COVER a = new COVER();
     a.setVisible(true);
     setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jadwal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new jadwal().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(jadwal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JButton insert;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kodejadwal;
    private javax.swing.JComboBox pilihfilm;
    private javax.swing.JComboBox ruangan;
    private javax.swing.JTable tabel1;
    private javax.swing.JTextField tanggal;
    private javax.swing.JButton update;
    private javax.swing.JComboBox waktu;
    // End of variables declaration//GEN-END:variables
}
