/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formadmin;

import controller.modelcinema;
import database.Koneksi;
import entitas.Film;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class MANAGEFILM extends javax.swing.JFrame {

    private int kode,hrg;
    private String gnr,nama;
    private modelcinema cinema;
    

    int dragx,dragy;
    public MANAGEFILM() throws SQLException {
        initComponents();
        this.cinema = new modelcinema();
        this.showTableFilm();
//        tabel.setModel(data07065.datafilm.viewTabel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        insert = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        genre = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        namafilm = new javax.swing.JTextField();
        kodefilm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/EXIT.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(370, 0, 50, 50);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 440, 360, 90);

        insert.setBackground(new java.awt.Color(0, 204, 204));
        insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/UPDATE.png"))); // NOI18N
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        getContentPane().add(insert);
        insert.setBounds(20, 580, 110, 50);

        delete.setBackground(new java.awt.Color(204, 0, 51));
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/DELETE.png"))); // NOI18N
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(150, 580, 110, 50);

        update.setBackground(new java.awt.Color(0, 204, 204));
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/INSERT.png"))); // NOI18N
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        getContentPane().add(update);
        update.setBounds(280, 580, 110, 50);

        jLabel6.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Harga");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 350, 80, 20);

        harga.setForeground(new java.awt.Color(255, 255, 255));
        harga.setText("price");
        harga.setOpaque(false);
        getContentPane().add(harga);
        harga.setBounds(40, 380, 320, 30);

        genre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ACTION", "HOROR", "ROMANCE", "ADVENTURE", "DRAMA", "KOMEDI" }));
        getContentPane().add(genre);
        genre.setBounds(40, 300, 320, 30);

        jLabel5.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Genre");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 270, 80, 20);

        jLabel4.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama Film");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 190, 80, 20);

        namafilm.setForeground(new java.awt.Color(255, 255, 255));
        namafilm.setText("film name");
        namafilm.setOpaque(false);
        getContentPane().add(namafilm);
        namafilm.setBounds(40, 220, 320, 30);

        kodefilm.setForeground(new java.awt.Color(255, 255, 255));
        kodefilm.setText("film code");
        kodefilm.setOpaque(false);
        getContentPane().add(kodefilm);
        kodefilm.setBounds(40, 140, 320, 30);

        jLabel2.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Kode Film");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 110, 80, 20);

        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel7MouseDragged(evt);
            }
        });
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 420, 650);

        jLabel3.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INPUT FILM");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 20, 220, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/FORM REG.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 650);

        setSize(new java.awt.Dimension(417, 651));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();
        int i = tabel.getSelectedRow();
        kodefilm.setText(model.getValueAt(i, 0).toString());
        
        try {
            this.cinema.updatefilm(Integer.parseInt(kodefilm.getText()),Integer.parseInt(harga.getText()));
            this.showTableFilm();
        } catch (SQLException ex) {
            Logger.getLogger(MANAGEFILM.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_updateActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) tabel.getModel();
        int i = tabel.getSelectedRow();
        Integer film = Integer.parseInt(model.getValueAt(i, 0).toString());
        try {
            this.cinema.deletefilm(film);
            this.showTableFilm();
        } catch (SQLException ex) {
            Logger.getLogger(MANAGEFILM.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_deleteActionPerformed

    private void kosong()
    {
        kodefilm.setText("");
        namafilm.setText("");
        harga.setText("");
    }
    private void showTableFilm() throws SQLException {
        DefaultTableModel dtmFilm = new DefaultTableModel(new String[]{
            "KODE FILM", "NAMA FILM", "GENRE", "HARGA"
        }, 0);
        dtmFilm.setRowCount(0);

        for (Film dp : this.cinema.getDataFilm()) {
            dtmFilm.addRow(new String[]{
                dp.getKode_Film().toString(), dp.getNama_Film(),
                dp.getGenre(), dp.getHarga().toString()
            });
        }
        this.tabel.setModel(dtmFilm);
    }

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        kode = Integer.parseInt(kodefilm.getText());
        nama = namafilm.getText();
        gnr = genre.getSelectedItem().toString();
        hrg = Integer.parseInt(harga.getText());
        Film film = new Film();
        try {
            film.setKode_Film(kode);
            film.setNama_Film(nama);
            film.setGenre(gnr);
            film.setHarga(hrg);
            this.cinema.insertfilm(film);
            this.showTableFilm();
            kosong();
        } catch (SQLException err) {
            System.out.println(err);
        }
//        data07065.datafilm.insert(kode, nama, gnr, hrg);
//        tabel.setModel(data07065.datafilm.viewTabel());
        
    }//GEN-LAST:event_insertActionPerformed

    private void jLabel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - dragx,y - dragy);
    }//GEN-LAST:event_jLabel7MouseDragged

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        dragx = evt.getX();
        dragy = evt.getY();
    }//GEN-LAST:event_jLabel7MousePressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            jadwal a = new jadwal();
            a.setVisible(true);
            setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(MANAGEFILM.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MANAGEFILM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MANAGEFILM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MANAGEFILM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MANAGEFILM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MANAGEFILM().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MANAGEFILM.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JComboBox genre;
    private javax.swing.JTextField harga;
    private javax.swing.JButton insert;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kodefilm;
    private javax.swing.JTextField namafilm;
    private javax.swing.JTable tabel;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
