/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formpembeli;

import controller.*;
import entitas.*;
import formadmin.*;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import tiket.bioskop.COVER;
 
/**
 *
 * @author Ilham Bayu Sabdani
 */
public class transaksi extends javax.swing.JFrame {

    /**
     * Creates new form MANAGEFILM
     */

    private modelpembeli beli;
    private modelcinema cinema;
    private ArrayList<Have> arrHV;
    private Integer hargatotal;

    
    Integer kodereg;
    String ddk;
    int dragx,dragy;
    public transaksi()
    {
        
    }
    
    public transaksi(String i, Integer x) throws SQLException {
        initComponents();
        this.cinema = new modelcinema();
        this.beli = new modelpembeli();
        this.arrHV = new ArrayList<>();
        this.hargatotal=0;
        this.showTableJadwal();
        this.showComboBoxJadwal();
        user.setText(i);
        user1.setText(x.toString());
//        tabel2.setModel(data07065.datajadwal.viewTabel());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel2 = new javax.swing.JTable();
        print = new javax.swing.JButton();
        item = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bnyk = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        kodetiket = new javax.swing.JTextField();
        user1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        tabel2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabel2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 320, 400, 200);

        print.setBackground(new java.awt.Color(0, 204, 204));
        print.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        print.setForeground(new java.awt.Color(255, 255, 255));
        print.setText("PILIH DUDUK");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print);
        print.setBounds(90, 590, 230, 23);

        getContentPane().add(item);
        item.setBounds(40, 190, 320, 30);

        jLabel10.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Pilih kode ");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 170, 80, 20);

        jLabel9.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Banyak tiket");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 230, 110, 20);

        jLabel5.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("kode reg");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(210, 60, 50, 20);

        bnyk.setForeground(new java.awt.Color(255, 255, 255));
        bnyk.setText("jumlah tiket");
        bnyk.setOpaque(false);
        bnyk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnykActionPerformed(evt);
            }
        });
        getContentPane().add(bnyk);
        bnyk.setBounds(40, 250, 320, 30);

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/EXIT.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(370, 0, 50, 50);

        jLabel4.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kode tiket");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 110, 110, 20);

        kodetiket.setForeground(new java.awt.Color(255, 255, 255));
        kodetiket.setText("kode tiket");
        kodetiket.setOpaque(false);
        kodetiket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kodetiketActionPerformed(evt);
            }
        });
        getContentPane().add(kodetiket);
        kodetiket.setBounds(40, 130, 320, 30);

        user1.setEditable(false);
        user1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        user1.setForeground(new java.awt.Color(255, 255, 255));
        user1.setOpaque(false);
        user1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user1ActionPerformed(evt);
            }
        });
        getContentPane().add(user1);
        user1.setBounds(260, 60, 100, 20);

        user.setEditable(false);
        user.setForeground(new java.awt.Color(255, 255, 255));
        user.setOpaque(false);
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        getContentPane().add(user);
        user.setBounds(260, 20, 100, 30);

        jLabel2.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("user");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(230, 20, 30, 30);

        jLabel7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel7MouseDragged(evt);
            }
        });
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel7MousePressed(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 420, 650);

        jLabel3.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("TRANSAKSI");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 0, 170, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/FORM REG.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 420, 650);

        setSize(new java.awt.Dimension(417, 651));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x - dragx,y - dragy);
    }//GEN-LAST:event_jLabel7MouseDragged

    private void jLabel7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MousePressed
        dragx = evt.getX();
        dragy = evt.getY();
    }//GEN-LAST:event_jLabel7MousePressed

    private void showuser(String x) throws SQLException
    {
        
    }
    
    private void showTableJadwal() throws SQLException {
        DefaultTableModel dtmJadwal = new DefaultTableModel(new String[]{
            "KODE JADWAL", "NAMA FILM", "TANGGAL TAYANG", "WAKTU TAYANG", "RUANG"
        }, 0);
        dtmJadwal.setRowCount(0);

        for (Jadwal jd : this.cinema.getDataJadwal()) {
            dtmJadwal.addRow(new String[]{
                jd.getKode_Jadwal().toString(),
                jd.getFilm().getNama_Film(),
                jd.getTgl_Tayang().toString(), 
                jd.getWktu_Tayang(),
                jd.getRuang()
            });
        }
        this.tabel2.setModel(dtmJadwal);
    }

    private void showComboBoxJadwal() throws SQLException {
        DefaultComboBoxModel dcbmJadwal = new DefaultComboBoxModel();

        for (Jadwal jd : this.cinema.getDataJadwal()) {
            dcbmJadwal.addElement(jd.getKode_Jadwal().toString() + ") " + jd.getFilm().getNama_Film());
        }
        this.item.setModel(dcbmJadwal);
        
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         COVER a = new COVER();
         a.setVisible(true);
         setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void kodetiketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kodetiketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kodetiketActionPerformed

    private void bnykActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnykActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bnykActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        Transaksi trans = new Transaksi();
        try {
            datahave();
            trans.setreg(beli.getDataReg().get(Integer.parseInt(user1.getText())-1));
            trans.setKode_Tiket(Integer.parseInt(kodetiket.getText()));
            trans.setBanyak(Integer.parseInt(bnyk.getText()));
            trans.setarrHave(arrHV);
            
            this.beli.inserttrans(trans);
            new duduk(user.getText(),Integer.parseInt(kodetiket.getText())).setVisible(true);
            setVisible(false);
        } catch (SQLException err) {
            System.out.println(err);
        }
        
    }//GEN-LAST:event_printActionPerformed

    private void datahave()
    {
        try {
            
            Have hv = new Have();
            hv.setjdwl(this.cinema.getDataJadwal().get(item.getSelectedIndex()));
            this.hargatotal += (this.cinema.getDataJadwal().get(item.getSelectedIndex()).getFilm().getHarga() * Integer.parseInt(bnyk.getText()));
            hv.settotal(this.hargatotal);

            this.arrHV.add(hv);
        } catch (SQLException ex) {
            Logger.getLogger(transaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        
    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userActionPerformed

    private void user1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bnyk;
    private javax.swing.JComboBox item;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kodetiket;
    private javax.swing.JButton print;
    private javax.swing.JTable tabel2;
    public static final javax.swing.JTextField user = new javax.swing.JTextField();
    private javax.swing.JTextField user1;
    // End of variables declaration//GEN-END:variables
}
